chef:
  build: .
  container_name: saltfactory-chefdk
  environment:
    - USER=ubuntu
  ports:
    - "8443:443"
    - "8000:80"
    - "8022:22"
  volumes:
    - "/Projects/Repositories/Saltfactory/docker-chefdk/data/hbn-chef-cookbooks:/home/ubuntu/chef-repo/cookbooks"
